# config.yaml
is_test: false
device: cuda
test_size: 0.4
val_size: 0.0
batch_size: 512
# * Grid-style sweep
search:
  seed: [0, 1, 2, 3, 4]
  dataset: [mnist, celeb]
  # dataset: [celeb]
  # * mnist: mlp and 10; celeb: conv and 50
  # model_type: [mlp, conv]
  # latent_dim: [10, 50]
  lr_ae: [2e-4]
  # num_epochs_ae: [30]
  lr_joint: [2e-4]
  # num_epochs_joint: [5]
  weight_decay: [1e-5]
  lambda_nll_vine: [1e-4, 1e-3]
  mtd_bidep: [chatterjee_xi, kendall_tau]
  mtd_kde: [tll]
  mtd_vine: [rvine]
  num_step_grid: [128]
  tau_thresh: [1e-2]
