# config.yaml
is_test: false
device: cuda
test_size: 0.5
val_size: 0.0
# * Grid-style sweep
search:
  seed: [0, 1, 2, 3]
  # dataset: [mnist]
  dataset: [svhn]
  # model_type: [mlp, conv]
  # latent_dim: [10, 50]
  lr_ae: [2e-4]
  # num_epochs_ae: [30]
  lr_joint: [1e-4]
  # num_epochs_joint: [5]
  weight_decay: [1e-5]
  lambda_nll_vine: [5e-5, 1e-5]
  mtd_bidep: [chatterjee_xi, kendall_tau]
  mtd_kde: [tll]
  mtd_vine: [rvine]
  num_step_grid: [128]
  tau_thresh: [1e-3]
